# Generated by Django 3.1.5 on 2021-02-05 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('translate', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='IRR', max_length=20, verbose_name='Currency Name')),
                ('decimal_number', models.IntegerField(default=0, verbose_name='Number of Digits in Decimal')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('translate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translate.dictionary')),
            ],
            options={
                'verbose_name': 'Price Currency',
                'verbose_name_plural': 'Price Currencies',
                'ordering': ('id', 'name', 'decimal_number', 'translate'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Product Code')),
                ('new_code', models.CharField(max_length=10, verbose_name='Product New Code')),
                ('size', models.CharField(max_length=100, verbose_name='Product Size')),
                ('package_qty', models.IntegerField(default=1, verbose_name='Product Package Quantity')),
                ('order', models.IntegerField(verbose_name='Product Order')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('id', 'product_type', 'code', 'new_code', 'size', 'unit', 'package_qty', 'order'),
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product Category Name')),
                ('order', models.IntegerField(verbose_name='Product Category Order')),
                ('image', models.ImageField(default='product/product_holder.jpg', upload_to='product/category/', verbose_name='Product Category Image')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('translate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translate.dictionary')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ('id', 'name', 'order', 'translate'),
            },
        ),
        migrations.CreateModel(
            name='ProductSubcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product Subcategory Name')),
                ('order', models.IntegerField(verbose_name='Product Subcategory Order')),
                ('image', models.ImageField(default='product/product_holder.jpg', upload_to='product/subcategory/', verbose_name='Product Subcategory Image')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productcategory')),
                ('translate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translate.dictionary')),
            ],
            options={
                'verbose_name': 'Product Subcategory',
                'verbose_name_plural': 'Product Subcategories',
                'ordering': ('id', 'category', 'name', 'order', 'translate'),
            },
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unit', max_length=100)),
                ('unit', models.CharField(max_length=100, verbose_name='Unit Name')),
                ('package', models.CharField(max_length=100, verbose_name='Package Name')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('translate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translate.dictionary')),
            ],
            options={
                'verbose_name': 'Product Unit',
                'verbose_name_plural': 'Product Units',
                'ordering': ('id', 'name', 'unit', 'package'),
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product Type Name')),
                ('specification', models.CharField(blank=True, max_length=100, verbose_name='Product Type Specification')),
                ('technical_detail', models.TextField(blank=True, verbose_name='Product Type Technical detail')),
                ('site_link', models.URLField(default='http://www.bts-co.com', verbose_name='Product URL to Site Page')),
                ('order', models.IntegerField(verbose_name='Product Type Order')),
                ('image', models.ImageField(default='product/product_holder.jpg', upload_to='product/products/', verbose_name='Product Type Image')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productsubcategory')),
                ('translate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translate.dictionary')),
            ],
            options={
                'verbose_name': 'Product Type',
                'verbose_name_plural': 'Product Types',
                'ordering': ('id', 'subcategory', 'name', 'specification', 'order', 'translate'),
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, verbose_name='Product Price List Name')),
                ('price', models.FloatField(default=1.0, verbose_name='Product Price')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.pricecurrency')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'Product Price',
                'verbose_name_plural': 'Product Prices',
                'ordering': ('id', 'tag', 'product', 'price', 'currency'),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.producttype'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productunit'),
        ),
    ]
