# Generated by Django 3.1.5 on 2021-01-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productunit',
            options={'ordering': ('id', 'name', 'unit', 'package'), 'verbose_name': 'Product Unit', 'verbose_name_plural': 'Product Units'},
        ),
        migrations.AddField(
            model_name='productunit',
            name='name',
            field=models.CharField(default='Unit', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pricecurrency',
            name='name',
            field=models.CharField(default='IRR', max_length=20, unique=True, verbose_name='Currency Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Product Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='new_code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Product New Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.IntegerField(verbose_name='Product Order'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(default='product/product_holder.jpg', upload_to='product/category/', verbose_name='Product Category Image'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Product Category Name'),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='image',
            field=models.ImageField(default='product/product_holder.jpg', upload_to='product/subcategory/', verbose_name='Product Subcategory Image'),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Product Subcategory Name'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='image',
            field=models.ImageField(default='product/product_holder.jpg', upload_to='product/products/', verbose_name='Product Type Image'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Product Type Name'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='specification',
            field=models.CharField(blank=True, max_length=100, verbose_name='Product Type Specification'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='technical_detail',
            field=models.TextField(blank=True, verbose_name='Product Type Technical detail'),
        ),
    ]
