# Generated by Django 3.1.5 on 2021-01-31 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0001_initial'),
        ('product', '0002_auto_20210131_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricecurrency',
            options={'ordering': ('id', 'name', 'decimal_number', 'translate'), 'verbose_name': 'Price Currency', 'verbose_name_plural': 'Price Currencies'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ('id', 'name', 'order', 'translate'), 'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='productsubcategory',
            options={'ordering': ('id', 'category', 'name', 'order', 'translate'), 'verbose_name': 'Product Subcategory', 'verbose_name_plural': 'Product Subcategories'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ('id', 'subcategory', 'name', 'specification', 'order', 'translate'), 'verbose_name': 'Product Type', 'verbose_name_plural': 'Product Types'},
        ),
        migrations.AddField(
            model_name='pricecurrency',
            name='translate',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='translate.dictionarymodel'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='translate',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='translate.dictionarymodel'),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='translate',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='translate.dictionarymodel'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='translate',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='translate.dictionarymodel'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='translate',
            field=models.ForeignKey(blank=True, default='translate', on_delete=django.db.models.deletion.CASCADE, to='translate.dictionarymodel'),
        ),
    ]
