# Generated by Django 3.1.5 on 2021-01-31 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0002_auto_20210131_1151'),
        ('product', '0003_auto_20210131_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricecurrency',
            name='translate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translate.dictionarymodel'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='translate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translate.dictionarymodel'),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='translate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translate.dictionarymodel'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='translate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translate.dictionarymodel'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='translate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translate.dictionarymodel'),
        ),
    ]
