# Generated by Django 3.1.5 on 2021-01-31 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0003_dictionary'),
        ('product', '0005_auto_20210131_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricecurrency',
            name='translate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translate.dictionary'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Product Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='new_code',
            field=models.CharField(max_length=10, verbose_name='Product New Code'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Product Category Name'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='translate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translate.dictionary'),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Product Subcategory Name'),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='translate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translate.dictionary'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Product Type Name'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='translate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translate.dictionary'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='name',
            field=models.CharField(default='Unit', max_length=100),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='translate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translate.dictionary'),
        ),
    ]
