# Generated by Django 3.1.5 on 2021-01-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionarymodel',
            name='item_name',
            field=models.TextField(default='Item', unique=True, verbose_name='Item Name'),
        ),
    ]
