# Generated by Django 3.1.5 on 2021-02-04 05:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionary',
            options={'ordering': ['id', 'item_name', 'fa_translate', 'en_translate', 'ar_translate', 'ru_translate', 'create_date'], 'verbose_name': 'Dictionary', 'verbose_name_plural': 'Dictionary'},
        ),
        migrations.AddField(
            model_name='dictionary',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create DateTime'),
            preserve_default=False,
        ),
    ]
