# Generated by Django 3.1.5 on 2021-01-31 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0003_dictionary'),
        ('product', '0006_auto_20210131_1248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DictionaryModel',
        ),
    ]
