# Generated by Django 3.1.5 on 2021-02-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='address',
            field=models.TextField(default='', verbose_name='User Address'),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='phone',
            field=models.CharField(default='', max_length=100, verbose_name='User Phone'),
        ),
    ]
