# Generated by Django 3.1.5 on 2021-02-05 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.useractivitymodel'),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.locationmodels'),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='phone',
            field=models.CharField(default=None, max_length=100, verbose_name='User Phone'),
        ),
    ]
