# Generated by Django 3.1.5 on 2021-02-06 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210206_1329'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LocationModels',
            new_name='LocationModel',
        ),
    ]
