# Generated by Django 3.1.5 on 2021-02-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210210_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='User Address'),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='firebase_token',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='User firebase Token'),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='login_token',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='User login Token'),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='User Phone'),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='rule',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='User Rule'),
        ),
    ]
